### ISSUE TITLE
Out of active subjects

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/Chimp-Zoo#73]
There are currently only 24 active subjects on C&S.  I'm guessing something didn't go as planned with the release of the next site?

**Comment by chrissnyder** [comment]
Looks to be more from https://api.zooniverse.org/projects/chimp/groups? Admittedly even there it's starting to get low and I should probably roll out the next site in a day or so.

**Comment by yshish** [comment]
Thanks, it is serious. Look at my last 6 recently classified videos.. All having the same ID. 
People are getting bored..
![](https://lh3.googleusercontent.com/-cX9pV6JSqaI/VbkOMszBUAI/AAAAAAAAIPM/nmhZkMOFJVE/s912-Ic42/ysh_2015-07-29.jpg)

**Comment by yshish** [comment]
We're out of data!

**Comment by brianaharder** [comment]
Yup, looks like site 7 is complete now, and site 8 and 9 are still inactive.

**Comment by chrissnyder** [comment]
Yep, working on this now, site 8 will be active shortly.

**Comment by chrissnyder** [comment]
Site 8 coming online now, 28,661 new videos!

**Comment by yshish** [comment]
AWESOME! That was fast :)

2015-07-29 21:20 GMT+02:00 Chris Snyder <notifications@github.com>:

**Comment by yshish** [comment]
It looks weird, I'm still getting the same videos as before, those which
were repeating.. all from the muddy-frost-7. Is it alright?

2015-07-29 21:28 GMT+02:00 Zuza Yshish <yshishka@gmail.com>:

**Comment by yshish** [comment]
After I finished 4 of them I finally started getting the new ones from
crimson-dew-8.
It seems to be solved.

2015-07-29 21:30 GMT+02:00 Zuza Yshish <yshishka@gmail.com>:

**Comment by yshish** [comment]
When I return to the classification page, the old 4 repeating videos go
first and then the new data come. Not always, but most of the time. Does it
happen to you too @
*brianaharder <https://github.com/brianaharder> ?*

2015-07-29 21:37 GMT+02:00 Zuza Yshish <yshishka@gmail.com>:

**Comment by yshish** [comment]
I'm not the only one with the repeating video experience after the new data set has been activated: http://talk.chimpandsee.org/#/boards/BCP000000e/discussions/DCP00009we

**Comment by brianaharder** [comment]
Testing, if I refresh the classification page, 8/20 times I get the videos
from site 7, which are always the same set of 4 repeats.

**Comment by chrissnyder** [comment]
Definitely getting S7 subjects back.

@parrish Looks like the redis sets are out of sync? `https://api.zooniverse.org/projects/chimp/groups/551ff93269736d5639020000/subjects` returns subjects with a state of complete.

**Comment by parrish** [comment]
Fixed

**Comment by DarrenMcRoy** [comment]
Um, not sure. People are getting dumped back to site 5 now. Including me. Are you sure... ?

**Comment by chrissnyder** [comment]
It's correct. The redis sets got out of sync, and there were a couple dozen
site 5 subjects still left in the system (76) to be exact. They'll be
cleared up shortly.

**Comment by DarrenMcRoy** [comment]
Cool. Thanks!!

**Comment by yshish** [comment]
Still getting mf7, it looks like the 4 repeating videos as before..

**Comment by yshish** [comment]
Sorry, these are different than the 4, but all are from mf7

**Comment by chrissnyder** [comment]
There are still some mf7 subjects left, so it's very possible to get videos
out of that site. Try clearing cache maybe?

**Comment by yshish** [comment]
It helped! Thanks.

**Comment by yshish** [comment]
There are still users who report getting mf7. Are they supposed to be displaying after 3 more days? http://talk.chimpandsee.org/#/boards/BCP0000007/discussions/DCP0000abw?page=1&comment_id=55be1340cc1b5727b5000080

**Comment by chrissnyder** [comment]
If they aren't getting duplicates, then yes. mf7 has 4,883 subjects left in
it.

https://api.zooniverse.org/projects/chimp/groups/551ff93269736d5639020000/

**Comment by yshish** [comment]
Then those mf7 seems to be OK. 

But there are even users getting occasional random videos more than once. For example, [jwidness](http://talk.chimpandsee.org/#/users/jwidness) had [ACP000571v](http://talk.chimpandsee.org/#/subjects/ACP000571v) and [ACP0004uys](http://talk.chimpandsee.org/#/subjects/ACP0004uys) twice each. She thought this was a problem related to running out of active videos, but crimson dew should have plenty of material.... (using her words) and someone else has got the same experience, just with different videos. 

http://talk.chimpandsee.org/#/boards/BCP000000e/discussions/DCP00009we?page=2&comment_id=55bfa09ccc1b5742ed000167

**Comment by chrissnyder** [comment]
The duplicates problem is something that keeps plaguing us, which I don't
think we'll have a solution for in the near future. Possibly clearing
cache/history and relogging in might help, but no guarantees.

And yea, crimson dev should have plenty of videos (about 20,000!)

**Comment by yshish** [comment]
Yeah, I've noticed it in other projects too :/ Hopefully it won't affect the results much. Thanks!
